name: Deploy to Pantheon

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PANTHEON_SSH_KEY }}

      - name: Add Pantheon host to known_hosts
        env:
          PANTHEON_SITE_ID: ${{ secrets.PANTHEON_SITE_ID }}
        run: |
          ssh-keyscan -p 2222 "codeserver.dev.${PANTHEON_SITE_ID}.drush.in" >> ~/.ssh/known_hosts

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql
          tools: composer:v2

      - name: Push to Pantheon
        env:
          PANTHEON_SITE_ID: ${{ secrets.PANTHEON_SITE_ID }}
        run: |
          git remote add pantheon "ssh://codeserver.dev.${PANTHEON_SITE_ID}@codeserver.dev.${PANTHEON_SITE_ID}.drush.in:2222/~/repository.git"
          echo "Pushing to Pantheon..."
          git push pantheon master
