name: Deploy to Pantheon

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql
          tools: composer:v2

      - name: Push to Pantheon
        env:
          PANTHEON_SITE_ID: e6e47d2e-63e9-4624-9d30-ae246a9130a7
        run: |
          git remote add pantheon ssh://codeserver.dev.${PANTHEON_SITE_ID}@codeserver.dev.${PANTHEON_SITE_ID}.drush.in:2222/~/repository.git
          echo "Pushing to Pantheon..."
          git push origin master
