name: Deploy to Pantheon

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push to Pantheon
        uses: pantheon-systems/push-to-pantheon@0.6.0
        with:
          ssh_key: ${{ secrets.PANTHEON_SSH_KEY }}
          machine_token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
          site: ${{ vars.PANTHEON_SITE_MACHINE_NAME }}